### PR TITLE
Added User-Agent

### PR DESCRIPTION
**Pull request by StephanGeorg**
Adding a user agent to prevent false negative in some environments:

https://runkit.com/57ed391ac15f95140033eeb2/57ffcfdc2109200014b79cf7 

Also added the error from request ti the callback.

### CODE REVIEW

**Comment by boblauer** [comment]
Just about to step out, but I will get this merged and published tomorrow morning.  Thanks for the pull.

**Comment by StephanGeorg** [comment]
Sry, checked again and I think there's another reason. Some environments return 403 for the HEAD request. I thought it had something to do with the missing user agent in the header.

**Comment by StephanGeorg** [comment]
According to https://runkit.com/57ed391ac15f95140033eeb2/57ffcfdc2109200014b79cf7 I think the most accurate way would be a GET request with User-Agent.

**Comment by StephanGeorg** [comment]
Ok, now I figured out you need at least

`var header = {
    "Accept": "text/html",
    "User-Agent": "Mozilla/5.0"
  };`

and a **GET** request to prevent the most false negative responses. The reason is that some configurations of webservers/firewalls respond with 403 for a HEAD request and/or missing headers, such as User-Agent and mime types. I checked some german bank websites for that.

**Comment by boblauer** [comment]
I'm hesitant to switch this to a GET request because that means the entire file will be downloaded, which is a lot of overhead if all you're trying to do is determine if a url exists or not.  I realize this means we get some false negatives, but if the vast majority of urls do work correctly, I think the trade off is worth it.

**Comment by StephanGeorg** [comment]
Yes, I understand this. I analyzed a lot of urls and had a false negative rate from around 8%. I will add another package url-exists-deep. Thanks for your time!

**Pull request closed without merging**
